# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        #self.setWindowFlag(QtCore.Qt.WindowMaximizeButtonHint, True)
        MainWindow.resize(1280, 900)

        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../res/ML4CYBER_Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # Splitter for left and right divisions
        self.splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        # Left division layout (for menu buttons)
        self.leftDivision = QtWidgets.QWidget()
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftDivision)
        self.leftLayout.setObjectName("leftLayout")
        self.splitter.addWidget(self.leftDivision)

        # Right division layout (initially empty)
        self.rightDivision = QtWidgets.QWidget()
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightDivision)
        self.rightLayout.setObjectName("rightLayout")
        self.splitter.addWidget(self.rightDivision)

        # Adding the splitter as the central widget
        MainWindow.setCentralWidget(self.splitter)

        # Set initial sizes for left and right divisions
        self.splitter.setSizes([100, 800])


        # Adding the buttons to the vertical layout

        # Add the label to the main layout
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.label.setGeometry(QtCore.QRect(0, 50, 100, 20))
        self.label.setText("ML Vinci Tool")
        self.label.setAlignment(QtCore.Qt.AlignCenter)  # Align label text to the center
        self.leftLayout.addWidget(self.label)

        # Dataset button
        self.btn_Datasets = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Datasets.setObjectName("btn_Datasets")
        self.btn_Datasets.setGeometry(QtCore.QRect(10, 100, 100, 30))
        self.leftLayout.addWidget(self.btn_Datasets)
        # Models button
        self.btn_Models = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Models.setObjectName("btn_Models")
        self.btn_Models.setGeometry(QtCore.QRect(10, 150, 100, 30))
        self.leftLayout.addWidget(self.btn_Models)
        # Prediction button
        self.btn_Predictions = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Predictions.setObjectName("btn_Predictions")
        self.btn_Predictions.setGeometry(QtCore.QRect(10, 200, 100, 30))
        self.leftLayout.addWidget(self.btn_Predictions)
        # adding new button to Visualize prediction results
        self.btn_Analysis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Analysis.setObjectName("btn_Analysis")
        self.btn_Analysis.setGeometry(QtCore.QRect(10, 250, 100, 30))
        self.leftLayout.addWidget(self.btn_Analysis)
        # adding new button to Visualize input dataset results
        self.btn_Visualize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Visualize.setObjectName("btn_Visualize")
        self.btn_Visualize.setGeometry(QtCore.QRect(10, 250, 100, 30))
        self.leftLayout.addWidget(self.btn_Visualize)
        # HELP button
        self.btn_Help = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Help.setObjectName("btn_Help")
        self.btn_Help.setGeometry(QtCore.QRect(10, 300, 100, 30))
        self.leftLayout.addWidget(self.btn_Help)
        self.leftLayout.addWidget(QtWidgets.QWidget()) # adding a spacer
        self.leftLayout.addWidget(QtWidgets.QWidget())  # adding a spacer

        #font settings for all buttons
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(30)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:3px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 30pt "Bauhaus 93";\n'
            "    font-weight: bold;\n"
            "    padding:5px 3px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.label.setObjectName("label")

        font = QtGui.QFont()

        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_Datasets.setFont(font)
        self.btn_Datasets.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:3px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 12pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:5px 3px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Datasets.setObjectName("btn_Datasets")

        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_Models.setFont(font)
        self.btn_Models.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:3px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 12pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:5px 3px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Models.setObjectName("btn_Models")

        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_Predictions.setFont(font)
        self.btn_Predictions.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:3px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 12pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:5px 3px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Predictions.setObjectName("btn_Predictions")

        # button btn_Visualize
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_Analysis.setFont(font)
        self.btn_Analysis.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:3px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 12pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:5px 3px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Analysis.setObjectName("btn_Analysis")

        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_Visualize.setFont(font)
        self.btn_Visualize.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:3px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 12pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:5px 3px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Visualize.setObjectName("btn_Visualize")

        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_Help.setFont(font)
        self.btn_Help.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:3px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 12pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:5px 3px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Help.setObjectName("btn_Help")

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Set the desired height for the buttons
        button_height = 80

        # Set the height of each button
        self.btn_Datasets.setFixedHeight(button_height)
        self.btn_Models.setFixedHeight(button_height)
        self.btn_Predictions.setFixedHeight(button_height)
        self.btn_Analysis.setFixedHeight(button_height)
        self.btn_Visualize.setFixedHeight(button_height)
        self.btn_Help.setFixedHeight(button_height)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vinci ML Tool"))
        self.btn_Datasets.setText(_translate("MainWindow", "DATASETS"))
        self.btn_Models.setText(_translate("MainWindow", "MODEL TRAINING"))
        self.btn_Predictions.setText(_translate("MainWindow", "PREDICTIONS"))
        self.btn_Analysis.setText(_translate("MainWindow", "DATA ANALYSIS"))
        self.btn_Visualize.setText(_translate("MainWindow", "VISUALIZE PREDICTIONS"))
        self.btn_Help.setText(_translate("MainWindow", "HELP"))


import menu_res_rc
