# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualize.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_VisualizationWindow(object):
    def setupUi(self, VisualizationWindow):
        VisualizationWindow.setObjectName("VisualizationWindow")
        VisualizationWindow.resize(1280, 840)

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        VisualizationWindow.setPalette(palette)

        font = QtGui.QFont()
        font.setPointSize(10)
        VisualizationWindow.setFont(font)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/ML4CYBER_Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        VisualizationWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(VisualizationWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 39, 1211, 800))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        #horizontalLayout_1
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        #add button
        self.btn_LoadPredResults = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_LoadPredResults.setObjectName("btn_LoadPredResults")
        self.horizontalLayout_1.addWidget(self.btn_LoadPredResults)
        #add label
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_1.addWidget(self.label_1)
        #add textbox
        self.txtB_DatasetPath = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtB_DatasetPath.setEnabled(True)
        self.txtB_DatasetPath.setReadOnly(True)
        self.txtB_DatasetPath.setObjectName("txtB_DatasetPath")
        self.horizontalLayout_1.addWidget(self.txtB_DatasetPath)
        #add the entire horizontalLayout_1
        self.verticalLayout.addLayout(self.horizontalLayout_1)

        #horizontalLayout_2
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # button 1
        self.btn_Vis_ConfMatrix = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Vis_ConfMatrix.setObjectName("btn_Vis_ConfMatrix")
        self.horizontalLayout_2.addWidget(self.btn_Vis_ConfMatrix)
        # button 2
        self.btn_Vis_ROC = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Vis_ROC.setObjectName("btn_Vis_ROC")
        self.horizontalLayout_2.addWidget(self.btn_Vis_ROC)
        # button 3
        self.btn_Vis_PRC = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Vis_PRC.setObjectName("btn_Vis_PRC")
        self.horizontalLayout_2.addWidget(self.btn_Vis_PRC)
        '''# button 4
        self.btn_SavePlot = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_SavePlot.setObjectName("btn_SavePlot")
        self.horizontalLayout_2.addWidget(self.btn_SavePlot)'''
        # add the entire horizontalLayout_2
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        # horizontalLayout_4
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        # button 1
        self.btn_SavePlot = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_SavePlot.setObjectName("btn_SavePlot")
        self.horizontalLayout_4.addWidget(self.btn_SavePlot)
        # button 2
        self.btn_Help = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Help.setObjectName("btn_Help")
        self.horizontalLayout_4.addWidget(self.btn_Help)
        # add the entire horizontalLayout_4
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        # horizontalLayout_3
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        # Locate the plotCanvas widget created in Qt Designer
        # Initialize FigureCanvas
        self.plotCanvas = FigureCanvas(Figure())
        self.plotCanvas.setGeometry(QtCore.QRect(30, 100, 300, 300))
        self.plotCanvas.setObjectName("plotCanvas")
        # Add plotCanvas to horizontalLayout_3
        self.horizontalLayout_3.addWidget(self.plotCanvas)
        # add the entire horizontalLayout_3
        self.verticalLayout.addLayout(self.horizontalLayout_3)



        VisualizationWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(VisualizationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        VisualizationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VisualizationWindow)
        self.statusbar.setObjectName("statusbar")
        VisualizationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VisualizationWindow)
        QtCore.QMetaObject.connectSlotsByName(VisualizationWindow)

    def retranslateUi(self, VisualizationWindow):
        _translate = QtCore.QCoreApplication.translate
        VisualizationWindow.setWindowTitle(_translate("VisualizationWindow", "Visualizations | Vinci ML Tool"))
        self.label_1.setText(_translate("VisualizationWindow", "Path:"))
        self.btn_LoadPredResults.setText(_translate("VisualizationWindow", "Load Prediction Results"))
        self.btn_Vis_ConfMatrix.setText(_translate("VisualizationWindow", "Confusion Matrix"))
        self.btn_Vis_ROC.setText(_translate("VisualizationWindow", "ROC Curve"))
        self.btn_Vis_PRC.setText(_translate("VisualizationWindow", "Precision Recall Curve"))
        self.btn_SavePlot.setText(_translate("VisualizationWindow", "Save Plot"))
        self.btn_Help.setText(_translate("VisualizationWindow", "Help"))

import menu_res_rc
